### ISSUE TITLE
Empty Marmiton.search

### ISSUE THREAD

**Issue by Axxiar** [remaudcorentin-dev/python-marmiton#18]
Maybe i missed something but is it normal if the Marmiton.search() in `example.py` is empty ?

![image](https://user-images.githubusercontent.com/70155662/116579358-9937ab80-a912-11eb-8cc3-a845750cce5c.png)

**Comment by mimoun-mohamed-lab** [comment]
I have the same problem. I think it doesn't work because the website changed and the scrapper is no longer maintained.

**Comment by Axxiar** [comment]
sadly :(

i'm closing this because I don't think that the scrapper will be working again
