### ISSUE TITLE
Error with marmiton.get

### ISSUE THREAD

**Issue by guillaumecostanza** [remaudcorentin-dev/python-marmiton#2]
Hi !

Hi have the following error when running the provider example in a fresh install :

site-packages/marmiton/__init__.py", line 79, in get
    name = soup.find("h1", {"class", "main-title "}).get_text().strip(' \t\n\r')
AttributeError: 'NoneType' object has no attribute 'get_text'

Thanks for the package anyway !

**Comment by YanisK33** [comment]
Hi!
I have the same issue...
Do you hopefully find a fix for it ?

**Comment by CVhp** [comment]
Hi! 
You can change the line : 
main_data = soup.find("div", {"class": "m_content_recette_main"})
by : 
main_data = soup.find("div", {"class": "content-recipe"})

I also had to remove the last "/" of this url : 
base_url = "http://www.marmiton.org" in __init__.py line 72

I hope it will help you.

**Comment by remaudcorentin-dev** [comment]
Fixed in last version (0.4.2)
